# RunPod.io
path: /workspace/yolov8_mag/data/dataset/ALL
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# MAC
#path: /Users/jankovic/Documents/yolov8/data/dataset/ALL
#train: images/train  # train images (relative to 'path')
#val: images/val  # val images (relative to 'path')

# Windows
#path: C:\Users\jank\Documents\Seafile\yolov8_new_location\data\dataset\ALL\
#train: images\train\  # train images (relative to 'path')
#val: images\val\  # val images (relative to 'path')

# Keypoints
kpt_shape: [1, 3]  # [number of keypoints in data, number of dim]
flip_idx: [0] # What is the correct index when flipping image

# Classes
names:
  0: sTMA #knee
  1: sTMA #knee
  2: FHC #hip
  3: sFDMA #knee
  4: sFDMA #knee
  5: TKC #knee
  6: TML #ankle
  7: FNOC #knee
  8: aF1 #femur


