# MAC
path: /Users/jankovic/Documents/yolov8/data/dataset/ALL
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Windows
#path: C:\Users\jank\Documents\Seafile\yolov8_new_location\data\dataset\ALL\
#train: images\train\  # train images (relative to 'path')
#val: images\val\  # val images (relative to 'path')

# Keypoints
kpt_shape: [1, 3]  # [number of keypoints in data, number of dim]
#v datoteki class.names definiraš imena točk
flip_idx: [0] # What is the correct index when flipping image
#flip_idx: [0, 1, 2, 3]

# Classes
names:
  0: FHC #hip
  1: TKC #knee
  2: TML #ankle
  3: FNOC #knee
  4: aF1 #femur


